domain: shuigel.github.io
url: https://shuigel.github.io
baseurl: "/docs" 

title: shuigen's homepage
email: shuigen@u.nus.edu
description: >- 
  This is Shuigen's homepage.

theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
